spring.application.name=ResearchGrid

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/research_grid
spring.datasource.username=postgres
spring.datasource.password=123

# Hibernate (Spring Data JPA) Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true